### ISSUE TITLE
add platinum searcher

### ISSUE THREAD

**Issue by jodaka** [leonid-shevtsov/SearchInProject_SublimeText#24]
Would be nice to have an ability to use pt (the platinum searcher) https://github.com/monochromegane/the_platinum_searcher within Sublime using this plugin as well.  I fiddled a bit trying to configure this plugin to use ack, but point ack executable to be a reference for pt. No luck.

**Comment by leonid-shevtsov** [comment]
Thanks for the suggestion! I've added Platinum Searcher and released version 1.7.0 - use `the_platinum_searcher` as your search engine.

**Comment by jodaka** [comment]
That was quick! Thanks!
