### ISSUE TITLE
pass arguments to search engine to ignore case

### ISSUE THREAD

**Issue by jeremysimmons** [leonid-shevtsov/SearchInProject_SublimeText#25]
How can I pass an argument to the search engine like /i to ignore case?

**Comment by AllanLRH** [comment]
Check the settings, it should be there.

**Comment by wujiyoung** [comment]
How can I pass explicit arguments when I want to search in different ways ?

**Comment by AllanLRH** [comment]
I don't think you can. You can pass arguments in the [settings](https://github.com/leonid-shevtsov/SearchInProject_SublimeText/blob/master/SearchInProject.sublime-settings), so I think your best best is to use per-project settings.

**Comment by wujiyoung** [comment]
Thank you !
I am openning another issue to post my problem.
