### ISSUE TITLE
Opens new file with title "D"

### ISSUE THREAD

**Issue by benjamindoe** [leonid-shevtsov/SearchInProject_SublimeText#42]
When I'm using Search In Project with pt on Windows, Sublime creates a new file when I try to open a file from the quick select menu.

![image](https://user-images.githubusercontent.com/15779219/30171807-dde290d8-93ea-11e7-9e66-51d00530ca6c.png)

![image](https://user-images.githubusercontent.com/15779219/30171866-0132d8e0-93eb-11e7-875c-8f8f5d443b2c.png)

Only have pt in my user settings

**Comment by dbobak** [comment]
Confirming the issue. It looks like SearchInProject cannot interpret the windows path.
