### ISSUE TITLE
Use the key binding on Windows,  the panel doesn't show up

### ISSUE THREAD

**Issue by iamfaith** [leonid-shevtsov/SearchInProject_SublimeText#45]
Env:
Sublime Text 2
Windows 10 64-bit

Problem:
Above. Even reading README I cannot find the “Search in Project” command so I cannot use it. 
Thanks for your amazing plugin.

**Comment by kavika13** [comment]
It's in the command palette. Did you check there?
Did you try restarting? A lot of sublime text plugins require that.
