### ISSUE TITLE
ImportError: No module named 'searchengines.ag

### ISSUE THREAD

**Issue by achamess** [leonid-shevtsov/SearchInProject_SublimeText#48]
I just installed this package in ST3 on Mac Build 3143
`Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "/Users/alex/Library/Application Support/Sublime Text 3/Packages/Search in Project/search_in_project.py", line 46, in run
    __import__("searchengines.%s" % self.engine_name)
ImportError: No module named 'searchengines.ag'
`

**Comment by achamess** [comment]
I fixed the problem. In the `/searchengines` directory, the file is called `the_silver_searcher.py` and the main .py file is looking for `searchengines.ag`. So I changed the name to `ag.py`. You might want to change this.

**Comment by Suppasit** [comment]
I had the same issue on Debian(9.4)-stretch. By following @achamess  comment I can fix the error.
